# cSpell:ignore gomod

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      pages-and-artifact-actions:
        patterns:
          - "actions/*pages*"
          - "actions/*-artifact"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
