#!/bin/sh

OLD_PWD=$(pwd)
LANED_PWD=$(realpath "${0}.d")

trap 'set +x; cd "$OLD_PWD" >/dev/null 2>&1; rm -rf $TMP >/dev/null 2>&1' 0
trap 'exit 2' 1 2 3 15

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  cat lane.d/help.md
  exit 0
fi

if [ "$1" = "-v" ] || [ "$1" = "--version" ] || [ "$1" = "version" ]; then
  echo "Version: ${VERSION:-unreleased}"
  exit 0
fi

while [ ! -d lanes ] && [ ! "$(pwd)" = '/' ]; do
  cd ..
done

display_lanes() {
  echo "The available lanes are:"
  if [ -d lanes ]; then
    find lanes -type f -mindepth 1 -maxdepth 1 | sed 's|^lanes/||g;s|^|  |g'
  else
    echo '  No lanes found.'
  fi
}

if [ -z "$1" ]; then
  display_lanes
  exit 1
fi

builtin_lane="${LANED_PWD}/$1/"
if [ -d "$builtin_lane" ]; then
  shift

  for i in "$@"; do
    if [ "$i" = "-h" ]; then
      grep -v '^```' <"$builtin_lane/help.md"
      exit 0
    fi
  done

  set +e
  sh "$builtin_lane/run.sh" "$@"
  status=$?
  if [ $status -eq 111 ]; then
    grep -v '^```' <"$builtin_lane/options.md"
    exit 1
  fi
  exit $status
fi

user_lane="./lanes/$1"
if [ -f "$user_lane" ]; then
  shift
  sh "$user_lane" "$@"
  exit 0
fi

echo "Unrecognized lane: '${1}'"
display_lanes
exit 10
