#!/bin/sh

OLD_PWD=$(pwd)
LANED_PWD=$(realpath "${0}.d")

echo 'Warning: lane is deprecated, see help for details' >&2
trap 'set +x; cd "$OLD_PWD" >/dev/null 2>&1;' 0
trap 'exit 2' 1 2 3 15

if [ "$1" = "completion" ]; then
  if [ "$2" = "zsh" ] || [ "$2" = "bash" ]; then
    cat "${LANED_PWD}/completion.$2.dotrc"
    exit $?
  else
    echo "You must specify either 'zsh' or 'bash' completions" >&2
    exit 1
  fi
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  grep -v '^```' <"${LANED_PWD}/help.md"
  exit 0
fi

if [ "$1" = "-v" ] || [ "$1" = "--version" ] || [ "$1" = "version" ]; then
  echo "Version: ${VERSION:-unreleased}"
  exit 0
fi

while [ ! -d lanes ] && [ ! "$(pwd)" = '/' ]; do
  cd ..
done

list_lanes() {
  find lanes -mindepth 1 -maxdepth 1 -type f | sed 's|^lanes/||g' | sort
}

display_lanes() {
  echo "The available lanes are:"
  if [ -d lanes ]; then
    list_lanes | sed 's|^|  |g'
  else
    echo '  No lanes found.'
  fi
}

if [ -z "$1" ]; then
  display_lanes >&2
  exit 1
fi

if [ "$1" = "lanes" ]; then
  list_lanes
  exit 0
fi

builtin_lane="${LANED_PWD}/$1/"
if [ -d "$builtin_lane" ]; then
  shift

  for i in "$@"; do
    if [ "$i" = "-h" ]; then
      grep -v '^```' <"$builtin_lane/help.md"
      exit 0
    fi
  done

  set +e
  sh "$builtin_lane/run.sh" "$@"
  status=$?
  if [ $status -eq 111 ]; then
    grep -v '^```' <"$builtin_lane/options.md" >&2
    exit 1
  fi
  exit $status
fi

user_lane="./lanes/$1"
if [ -f "$user_lane" ]; then
  shift
  sh "$user_lane" "$@"
  exit 0
fi

echo "Unrecognized lane: '${1}'" >&2
display_lanes
exit 10
