#!/bin/sh

[ "$CURL_OVERRIDE" = "fail" ] && exit 22
[ -f "$CURL_OVERRIDE" ] || {
  echo "CURL_OVERRIDE is not a file: $CURL_OVERRIDE"
  exit 1
}

while getopts ":o:" OPTION; do
  case "$OPTION" in
  o)
    cat "$CURL_OVERRIDE" >"$OPTARG"
    exit 0
    ;;
  *) ;;
  esac
done

cat "$CURL_OVERRIDE"
