#!/bin/sh

_USAGE() {
cat << END
OPTIONS
    -h show this usage
    -o output path
    -i document id
    -t bearer token, see google-api-jwt-generate
    -f format, default csv
END
}

unset -v OUTPUT ID TOKEN
FORMAT='csv'
while getopts "hi:t:f:o:" option; do
  case $option in
    o) OUTPUT="$OPTARG" ;;
    i) ID="$OPTARG" ;;
    t) TOKEN="$OPTARG" ;;
    f) FORMAT="$OPTARG" ;;
    \?)
      echo "unknown option: $option"
      _USAGE
      exit 1
      ;;
    h)
      _USAGE
      exit 0
      ;;
  esac
done
shift $((OPTIND - 1))

if [ -z "$ID" ] || [ -z "$TOKEN" ] || [ -z "$OUTPUT" ]; then
    echo "Must provide output path, document id and authentication key."
    _USAGE
    exit 2
fi

if [ ! -x "$(command -v curl)" ]; then
  echo "Error: curl is not installed." >&2
  exit 3
fi

DIR=$(mktemp -dq)

trap 'set +x; rm -fr $DIR >/dev/null 2>&1' 0
trap 'exit 2' 1 2 3 15

url=$(printf 'https://docs.google.com/spreadsheets/d/%s/export?exportFormat=%s' "$ID" "$FORMAT")
header=$(printf 'Authorization: Bearer %s' "$TOKEN")

OUT=$(dirname "$OUTPUT")
mkdir -p "$OUT"
curl --silent --fail -L -o "$OUTPUT" --header "$header" "$url"
