#!/bin/sh

MAIN=$(echo "$1" | sed 's|[^0-9\.]||g')
CURRENT=$(echo "$2" | sed 's|[^0-9\.]||g')

if [ -z "$CURRENT" ]; then
    echo 'Was not given a current version'
    exit 1
fi

if [ -z "$MAIN" ]; then
    exit 0
fi

echo '::group::Resolved versions'
printf '%s - main version\n%s - current version\n' "$MAIN" "$CURRENT"
echo '::endgroup::'

[ "$MAIN" = "$CURRENT" ] && { echo 'Version must be changed.'; exit 10; }

VERIFY=$(printf '%s\n%s' "$MAIN" "$CURRENT" | sort -t '.' -k 1,1 -k 2,2 -k 3,3 -k 4,4 -g | tail -n1)
[ "$MAIN" = "$VERIFY" ] && { echo 'Version must be greater than version on main.'; exit 20; }

exit 0