name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  passing-tests:
    name: Passing tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test that passes
        run: |
          echo 'Test-in-tests'

  failing-tests:
    name: Failing tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test that fails
        run: |
          exit 2
