name: Tests

on:
  workflow_dispatch: {}

jobs:
  test-run:
    name: Test run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test that passes
        run: |
          echo 'Test-in-tests'

      - name: Test that fails
        run: |
          exit 1
