name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make test

  editorconfig-check:
    name: Editorconfig check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  dependabot-validate:
    name: Validate dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install check-jsonschema
        shell: bash
      - run: curl -o schema.json 'https://json.schemastore.org/dependabot-2.0.json'
        shell: bash
      - run: check-jsonschema --schemafile schema.json .github/dependabot.yml
        shell: bash

  workflow-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        with:
          tool_versions: |
            action-validator 0.6.0
      - name: Lint workflows
        run: find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) | xargs -I {} action-validator --verbose {}

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - unit-tests
      - editorconfig-check
      - dependabot-validate
      - workflow-validate

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0

  auto-merge-dependabot:
    name: Automerge Dependabot PR
    needs:
      - tests-succeeded
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
