# cSpell:ignore pipx jsonschema schemafile

name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: echo ${{ secrets.SMOKE_TEST_CREDENTIALS_B64 }} | base64 -d > credentials.json
        shell: bash
      - run: make test
        shell: bash

  documentation-tests:
    name: Documentation tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: make update-docs
        shell: bash
      - run: git diff --quiet --exit-code
        shell: bash

  editorconfig-check:
    name: Editorconfig check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
        shell: bash

  dependabot-validate:
    name: Validate dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pipx install check-jsonschema
        shell: bash
      - run: check-jsonschema --builtin-schema vendor.dependabot .github/dependabot.yml
        shell: bash

  workflow-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: asdf-vm/actions/install@v4
        with:
          tool_versions: |
            action-validator 0.6.0
      - name: Lint workflows
        run: find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) | xargs -I {} action-validator --verbose {}
        shell: bash

  wip-check:
    name: No 'fix me's check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: grep -RHin $(printf Zml4bWUK | base64 -d) . && exit 1 || exit 0 # had to hide the `f i x m e` inside of base64 to not trigger it here too

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - unit-tests
      - documentation-tests
      - editorconfig-check
      - dependabot-validate
      - workflow-validate
      - wip-check
    runs-on: ubuntu-latest
    steps:
      - name: Create token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: All clear
        run: exit 0
