name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make test
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: build/coverage.*
          if-no-files-found: error

  documentation-tests:
    name: Documentation tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make update-docs
        shell: bash
      - run: git diff --quiet --exit-code
        shell: bash

  editorconfig-check:
    name: Editorconfig check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
        shell: bash

  dependabot-validate:
    name: Validate dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install check-jsonschema
        shell: bash
      - run: curl -o schema.json 'https://json.schemastore.org/dependabot-2.0.json'
        shell: bash
      - run: check-jsonschema --schemafile schema.json .github/dependabot.yml
        shell: bash

  workflow-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        with:
          tool_versions: |
            action-validator 0.6.0
      - name: Lint workflows
        run: find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) | xargs -I {} action-validator --verbose {}
        shell: bash

  fixme-check:
    name: No FIXMEs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: grep -RHin fixme . && exit 1

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - unit-tests
      - documentation-tests
      - editorconfig-check
      - dependabot-validate
      - workflow-validate
      - fixme-check

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
