
name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  lane:
    name: Test Lane
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test missing argument
        run: |
          rm -rf lanes
          mkdir lanes

          set +e
          sh ./lane > result
          [ $? -eq 1 ] || exit 1
          echo 'The available lanes are:' > expected
          diff -q expected result || { echo "Unexpected difference:"; diff expected result; exit 1; }

      - name: Test help argument
        run: |
          rm -rf lanes
          mkdir lanes

          set +e
          sh ./lane -h > 1
          [ $? -eq 0 ] || exit 1

          sh ./lane --help > 2
          [ $? -eq 0 ] || exit 1

          sh ./lane help > 3
          [ $? -eq 0 ] || exit 1

          diff -q 1 2 || { echo "Unexpected difference:"; diff 1 2; exit 1; }
          diff -q 2 3 || { echo "Unexpected difference:"; diff 2 3; exit 1; }

      - name: Test version argument
        run: |
          rm -rf lanes

          set +e
          sh ./lane -v > 1
          [ $? -eq 0 ] || exit 1

          sh ./lane --version > 2
          [ $? -eq 0 ] || exit 1

          sh ./lane version > 3
          [ $? -eq 0 ] || exit 1

          diff -q 1 2 || { echo "Unexpected difference:"; diff 1 2; exit 1; }
          diff -q 2 3 || { echo "Unexpected difference:"; diff 2 3; exit 1; }

      - name: Test missing lane
        run: |
          rm -rf lanes
          mkdir lanes
          echo 'echo hi' > lanes/say-hi

          set +e
          sh ./lane say-bye > /dev/null
          [ $? -eq 10 ] || exit 1

      - name: Test configured lane
        run: |
          rm -rf lanes
          mkdir lanes
          echo 'echo hi' > lanes/say-hi

          set +e
          sh ./lane say-hi > result
          [ $? -eq 0 ] || exit 1
          echo 'hi' > expected
          diff -q expected result || { echo "Unexpected difference:"; diff expected result; exit 1; }

      - name: Test builtin lane
        run: |
          rm -rf lanes
          mkdir lanes
          echo 'echo hi' > lane.d/say-hi

          set +e
          sh ./lane say-hi > result
          [ $? -eq 0 ] || exit 1
          echo 'hi' > expected
          diff -q expected result || { echo "Unexpected difference:"; diff expected result; exit 1; }

      - name: Test builtin lane over configured lane
        run: |
          rm -rf lanes
          mkdir lanes
          echo 'echo false' > lanes/say
          echo 'echo true' > lane.d/say

          set +e
          sh ./lane say > result
          [ $? -eq 0 ] || exit 1
          echo 'true' > expected
          diff -q expected result || { echo "Unexpected difference:"; diff expected result; exit 1; }

  mobile-static-resources-images:
    name: Test Static Resources Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          mkdir ./empty-folder

      - name: Test missing arguments
        run: |
          set +e
          sh lane.d/mobile-static-resources-images > /dev/null
          [ $? -eq 2 ] || exit 1

      - name: Test missing input file
        run: |
          set +e
          sh lane.d/mobile-static-resources-images -o result > /dev/null
          [ $? -eq 2 ] || exit 1

      - name: Test missing output file
        run: |
          set +e
          sh lane.d/mobile-static-resources-images -i input > /dev/null
          [ $? -eq 2 ] || exit 1

      - name: Test non-existing input folder
        run: |
          set +e
          sh lane.d/mobile-static-resources-images -i ./non-existing-folder -o result > /dev/null
          [ $? -eq 3 ] || exit 1

      - name: Test empty asset folder
        run: |
          set +e
          sh lane.d/mobile-static-resources-images -i empty-folder -o result
          [ $? -eq 0 ] || exit 1
          diff -q .github/test-resources/mobile-static-resources-images/empty.swift result > /dev/null || { echo "Unexpected difference:"; diff .github/test-resources/mobile-static-resources-images/empty.swift result; exit 1; }

      - name: Test with asset folder
        run: |
          set +e
          sh lane.d/mobile-static-resources-images -i .github/test-resources/mobile-static-resources-images/assets -o result
          [ $? -eq 0 ] || exit 1
          diff -q .github/test-resources/mobile-static-resources-images/assets.swift result > /dev/null || { echo "Unexpected difference:"; diff .github/test-resources/mobile-static-resources-images/assets.swift result; exit 1; }

      - name: Test creating output folder
        run: |
          set +e
          sh lane.d/mobile-static-resources-images -i empty-folder -o will/be/created
          [ $? -eq 0 ] || exit 1
          [ -d "./will/be" ] || { echo "Output folder was not created"; exit 1; }

  mobile-update-translations:
    name: Test Update Translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test missing argument
        run: |
          set +e
          sh lane.d/mobile-update-translations > /dev/null
          [ $? -eq 2 ] || exit 1

      - name: Test missing configuration for missing input
        run: |
          set +e
          sh lane.d/mobile-update-translations -t ios -k 1 -m EN -o result.swift -c "4 DA result.DA.strings" -c "3 EN result.EN.strings"
          [ $? -eq 2 ] || exit 1

      - name: Test missing configuration for input not a file
        run: |
          set +e
          sh lane.d/mobile-update-translations -t ios -k 1 -m EN -o result.swift -c "4 DA result.DA.strings" -c "3 EN result.EN.strings" -i .github/test-resources/
          [ $? -eq 2 ] || exit 1

      - name: Test missing configuration for missing main language
        run: |
          set +e
          sh lane.d/mobile-update-translations -t ios -k 1 -o result.swift -c "4 DA result.DA.strings" -c "3 EN result.EN.strings" -i .github/test-resources/mobile-update-translations/configuration/input.csv
          [ $? -eq 2 ] || exit 1

      - name: Test missing configuration for missing key row
        run: |
          set +e
          sh lane.d/mobile-update-translations -t ios -m EN -o result.swift -c "4 DA result.DA.strings" -c "3 EN result.EN.strings" -i .github/test-resources/mobile-update-translations/configuration/input.csv
          [ $? -eq 2 ] || exit 1

      - name: Test missing configuration for missing output
        run: |
          set +e
          sh lane.d/mobile-update-translations -t ios -k 1 -m EN -c "4 DA result.DA.strings" -c "3 EN result.EN.strings" -i .github/test-resources/mobile-update-translations/configuration/input.csv
          [ $? -eq 2 ] || exit 1

      - name: Test ios output is created as expected
        run: |
          set +e
          sh lane.d/mobile-update-translations -t ios -k 1 -m EN -o result.swift -c "4 DA result.DA.strings" -c "3 EN result.EN.strings" -i .github/test-resources/mobile-update-translations/configuration/input.csv
          [ $? -eq 0 ] || exit 1
          diff -q .github/test-resources/mobile-update-translations/expected-ios/result.swift result.swift > /dev/null || { echo "Unexpected difference:"; diff .github/test-resources/mobile-update-translations/expected-ios/result.swift result.swift; exit 1; }
          diff -q .github/test-resources/mobile-update-translations/expected-ios/result.EN.strings result.EN.strings > /dev/null || { echo "Unexpected difference:"; diff .github/test-resources/mobile-update-translations/expected-ios/result.EN.strings result.EN.strings; exit 1; }
          diff -q .github/test-resources/mobile-update-translations/expected-ios/result.DA.strings result.DA.strings > /dev/null || { echo "Unexpected difference:"; diff .github/test-resources/mobile-update-translations/expected-ios/result.DA.strings result.DA.strings; exit 1; }

      - name: Test android output is created as expected
        run: |
          set +e
          sh lane.d/mobile-update-translations -t android -k 1 -c "4 DA result.DA.strings" -c "3 EN result.EN.strings" -i .github/test-resources/mobile-update-translations/configuration/input.csv
          [ $? -eq 0 ] || exit 1
          diff -q .github/test-resources/mobile-update-translations/expected-android/result.EN.strings result.EN.strings > /dev/null || { echo "Unexpected difference:"; diff .github/test-resources/mobile-update-translations/expected-android/result.EN.strings result.EN.strings; exit 1; }
          diff -q .github/test-resources/mobile-update-translations/expected-android/result.DA.strings result.DA.strings > /dev/null || { echo "Unexpected difference:"; diff .github/test-resources/mobile-update-translations/expected-android/result.DA.strings result.DA.strings; exit 1; }

  shell-run-github-workflow-tests:
    name: Test Shell Run Github Workflow Tests (always skipped on GitHub)
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v3

      - name: Test non-existing file
        run: |
          set +e
          sh lane.d/shell-run-github-workflow-tests -i ./non-existing-file > /dev/null
          [ $? -eq 1 ] || exit 1
      - name: Test running tests
        run: |
          sh lane.d/shell-run-github-workflow-tests -i .github/test-resources/shell-run-github-workflow-tests/test.yaml
  
  shell-github-action-semver-compare:
    name: Test Shell Github Action Semver Compare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test missing arguments
        run: |
          set +e
          sh lane.d/shell-github-action-semver-compare > /dev/null
          [ $? -eq 2 ] || exit 1

      - name: Test missing main version argument
        run: |
          set +e
          sh lane.d/shell-github-action-semver-compare -c "0.0.0" > /dev/null
          [ $? -eq 2 ] || exit 1

      - name: Test missing current version argument
        run: |
          set +e
          sh lane.d/shell-github-action-semver-compare -m "0.0.0" > /dev/null
          [ $? -eq 2 ] || exit 1

      - name: Test matching versions
        run: |
          set +e
          sh lane.d/shell-github-action-semver-compare -m "0.0.0" -c "0.0.0" > /dev/null
          [ $? -eq 10 ] || exit 1

      - name: Test descending versions
        run: |
          set +e
          sh lane.d/shell-github-action-semver-compare -m "1.2.3" -c "0.0.0" > /dev/null
          [ $? -eq 20 ] || exit 1

      - name: Test ascending versions
        run: |
          set +e
          sh lane.d/shell-github-action-semver-compare -m "1.2.3" -c "3.2.1" > /dev/null
          [ $? -eq 0 ] || exit 1

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Files must be executable for shellcheck action to check them
      run: |
        test $(find lane.d lane -type f ! -perm +ugo+x | wc -c) -eq 0 || (find lane.d lane -type f ! -perm +ugo+x && exit 1)

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './lane.d'
        additional_files: 'lane'

  tests-succeeded:
    name: Tests Succeeded
    needs: [lane, mobile-static-resources-images, mobile-update-translations, shell-github-action-semver-compare, shellcheck]
    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0